run:
  timeout: 30m
  skip-files:
    - "^zz_generated.*"

issues:
  max-same-issues: 0

linters:
  disable-all: true
  enable: # please keep this alphabetized
    - deadcode
    - ineffassign
    - staticcheck
    - unused
    - varcheck
linters-settings: # please keep this alphabetized
  staticcheck:
    go: "1.17"
    checks: [
      "all",
      "-S1*",   # Omit code simplifications for now.
      "-ST1*",  # Mostly stylistic, redundant w/ golint
      "-SA5011" # Possible nil pointer dereference
    ]
  unused:
    go: "1.17"
