sudo: false

language: go

matrix:
  include:
    - go: 1.4

install:
  - go get github.com/tools/godep
  - ./hack/travis/install-etcd.sh
  - ./hack/build-go.sh
  - export PATH=$GOPATH/bin:./third_party/etcd:$PATH

script:
  - make verify BRANCH=$TRAVIS_BRANCH
  - ./hack/test-go.sh
  - ./hack/test-integration.sh
  - ./hack/test-cmd.sh

notifications:
  irc: "chat.freenode.net#kubernetes-dev"
  slack: kubernetes:PHPPkljtEsHXED6xl9IfOvKe
