sudo: false

language: go

matrix:
  include:
    - go: 1.4
      env: LMKTFY_TEST_API_VERSIONS="v1beta1"
    - go: 1.3
      env: LMKTFY_TEST_API_VERSIONS="v1beta3"

install:
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - go get github.com/mattn/goveralls
  - ./hack/travis/install-etcd.sh
  - ./hack/verify-gofmt.sh
  - ./hack/verify-boilerplate.sh
  - ./hack/verify-description.sh
  - ./hack/travis/install-std-race.sh
  - ./hack/build-go.sh
  - GOPATH=$PWD/Godeps/_workspace:$GOPATH go install ./...
  - PATH=$HOME/gopath/bin:./third_party/etcd:$PATH ./hack/verify-gendocs.sh

script:
  - LMKTFY_RACE="-race" LMKTFY_COVER="y" LMKTFY_GOVERALLS_BIN="$HOME/gopath/bin/goveralls" LMKTFY_TIMEOUT='-timeout 300s' LMKTFY_COVERPROCS=8 LMKTFY_TEST_API_VERSIONS=$LMKTFY_TEST_API_VERSIONS ./hack/test-go.sh -- -p=2
  - PATH=$HOME/gopath/bin:./third_party/etcd:$PATH ./hack/test-cmd.sh
  - PATH=$HOME/gopath/bin:./third_party/etcd:$PATH LMKTFY_TEST_API_VERSIONS=$LMKTFY_TEST_API_VERSIONS ./hack/test-integration.sh

notifications:
  irc: "chat.freenode.net#google-containers"
