language: go

os:
  - linux
  - osx

go:
  - 1.3
  - 1.2
  - 1.3
  - tip

install: 
  - ./hack/ci.sh
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/coreos/etcd
  - ./hack/verify-gofmt.sh
  - ./hack/verify-boilerplate.sh
  - ./hack/install-std-race.sh
  - ./hack/build-go.sh

script:
  - ./hack/test-go.sh
  - PATH=$HOME/gopath/bin:$PATH ./hack/test-cmd.sh
  - PATH=$HOME/gopath/bin:$PATH ./hack/integration-test.sh

notifications:
  irc: "chat.freenode.net#google-containers"
