sudo: false

language: go

matrix:
  include:
    - go: 1.4
      env:
        - KUBE_TEST_API_VERSIONS="v1"
          KUBE_TEST_ETCD_PREFIXES="registry"

install:
  - go get github.com/tools/godep
  - ./hack/travis/install-etcd.sh
  - ./hack/verify-gofmt.sh
  - ./hack/verify-boilerplate.sh
  - ./hack/verify-description.sh
  - ./hack/travis/install-std-race.sh
  - ./hack/build-go.sh
  - PATH=$GOPATH/bin:$PATH godep go install ./...
  - PATH=$GOPATH/bin:$PATH ./hack/verify-generated-conversions.sh
  - PATH=$GOPATH/bin:$PATH ./hack/verify-generated-deep-copies.sh
  - PATH=$GOPATH/bin:./third_party/etcd:$PATH ./hack/verify-gendocs.sh
  - PATH=$GOPATH/bin:./third_party/etcd:$PATH ./hack/verify-swagger-spec.sh

notifications:
  irc: "chat.freenode.net#google-containers"
