language: go

go:
  - 1.3
  - 1.2
  - tip

install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/coreos/etcd
  - go get github.com/tools/godep
  - PATH=$HOME/gopath/bin:$PATH make check_gofmt
  - ./hack/verify-boilerplate.sh
  - ./hack/install-std-race.sh
  - PATH=$HOME/gopath/bin:$PATH make all

script:
  - PATH=$HOME/gopath/bin:$PATH make test
  - PATH=$HOME/gopath/bin:$PATH ./hack/test-cmd.sh
  - PATH=$HOME/gopath/bin:$PATH ./hack/test-integration.sh

notifications:
  irc: "chat.freenode.net#google-containers"
