apiVersion: multicluster.x-k8s.io/v1alpha1
kind: Work
metadata:
  name: example
  namespace: some-ns
spec:
  workload:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-deployment
        namespace: different-ns
    - apiVersion: v1
      kind: Secret
      metadata:
        name: my-secret
        namespace: different-ns
