timeout: 10800s

substitutions:
  { "_ARCH": "amd64",
    "_IMAGE": "gcr.io/k8s-image-staging/kube-addon-manager",
    "_VERSION": "v8.6"}

steps:
- name: gcr.io/cloud-builders/git
  id: git-clone
  entrypoint: bash
  args:
  - "-c"
  - |
    set -ex
    mkdir -p /workspace/src/k8s.io
    mkdir -p /workspace/tmp-${_ARCH}
    cd /workspace/src/k8s.io
    git clone https://github.com/kubernetes/kubernetes.git

- name: gcr.io/k8s-image-staging/make
  id: make-build
  entrypoint: bash
  dir: "/workspace/src/k8s.io/kubernetes/cluster/addons/addon-manager"
  args:
  - "-c"
  - |
    set -ex
    TEMP_DIR=/workspace/tmp-${_ARCH} make build

- name: gcr.io/cloud-builders/docker
  id: docker-build
  dir: "/workspace/src/k8s.io/kubernetes/cluster/addons/addon-manager"
  args: ["build", "--pull", "-t", "${_IMAGE}:${_VERSION}", "/workspace/tmp-${_ARCH}"]

images:
- "${_IMAGE}:${_VERSION}"
