#cloud-config

write_files:
  - path: /etc/cloud.conf
    permissions: 0600
    content: |
      [Global]
      auth-url = OS_AUTH_URL
      username = OS_USERNAME
      api-key = OS_PASSWORD
      tenant-id = OS_TENANT_NAME
      region = OS_REGION_NAME
      [LoadBalancer]
      subnet-id = 11111111-1111-1111-1111-111111111111
  - path: /opt/bin/git-lmktfy-nginx.sh
    permissions: 0755
    content: |
      #!/bin/bash
      git clone https://github.com/thommay/lmktfy_nginx /opt/lmktfy_nginx
      /usr/bin/cp /opt/.lmktfy_auth /opt/lmktfy_nginx/.lmktfy_auth
      /opt/lmktfy_nginx/git-lmktfy-nginx.sh
  - path: /opt/bin/download-release.sh
    permissions: 0755
    content: |
      #!/bin/bash
      OBJECT_URL="CLOUD_FILES_URL"
      echo "Downloading release ($OBJECT_URL)"
      wget "${OBJECT_URL}" -O /opt/lmktfy.tar.gz
      echo "Unpacking release"
      rm -rf /opt/lmktfy || false
      tar xzf /opt/lmktfy.tar.gz -C /opt/
  - path: /opt/.lmktfy_auth
    permissions: 0600
    content: |
      LMKTFY_USER:LMKTFY_PASSWORD

coreos:
  etcd:
    name: lmktfy-master
    discovery: https://discovery.etcd.io/DISCOVERY_ID
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
    peer-bind-addr: $private_ipv4:7001

  fleet:
    public-ip: $private_ipv4
    metadata: lmktfy_role=master

  update:
    reboot-strategy: etcd-lock

  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: download-release.service
      command: start
      content: |
        [Unit]
        Description=Downloads LMKTFY Release
        After=network-online.target
        Requires=network-online.target
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/bash /opt/bin/download-release.sh
    - name: master-apiserver.service
      command: start
      content: |
        [Unit]
        Description=LMKTFY API Server
        Documentation=https://github.com/GoogleCloudPlatform/lmktfy
        After=network-online.target
        Requires=network-online.target
        After=download-release.service
        Requires=download-release.service
        [Service]
        ExecStartPre=/usr/bin/ln -sf /opt/lmktfy/server/bin/lmktfy-apiserver /opt/bin/lmktfy-apiserver
        ExecStart=/opt/bin/lmktfy-apiserver --address=127.0.0.1 --port=8080 --etcd_servers=http://127.0.0.1:4001 --portal_net=PORTAL_NET --logtostderr=true --cloud_provider=rackspace --cloud_config=/etc/cloud.conf --v=2
        Restart=always
        RestartSec=2
    - name: master-controller-manager.service
      command: start
      content: |
        [Unit]
        Description=LMKTFY Controller Manager
        Documentation=https://github.com/GoogleCloudPlatform/lmktfy
        After=network-online.target
        Requires=network-online.target
        After=master-apiserver.service
        Requires=master-apiserver.service
        [Service]
        ExecStartPre=/usr/bin/ln -sf /opt/lmktfy/server/bin/lmktfy-controller-manager /opt/bin/lmktfy-controller-manager
        ExecStart=/opt/bin/lmktfy-controller-manager --master=127.0.0.1:8080 --logtostderr=true --cloud_provider=rackspace --cloud_config=/etc/cloud.conf --v=2
        Restart=always
        RestartSec=2
    - name: master-scheduler.service
      command: start
      content: |
        [Unit]
        Description=LMKTFY Scheduler
        Documentation=https://github.com/GoogleCloudPlatform/lmktfy
        After=network-online.target
        Requires=network-online.target
        After=master-apiserver.service
        Requires=master-apiserver.service
        [Service]
        ExecStartPre=/usr/bin/ln -sf /opt/lmktfy/server/bin/lmktfy-scheduler /opt/bin/lmktfy-scheduler
        ExecStart=/opt/bin/lmktfy-scheduler --master=127.0.0.1:8080 --logtostderr=true
        Restart=always
        RestartSec=10
    - name: master-register.service
      command: start
      content: |
        [Unit]
        Description=LMKTFY Registration Service
        Documentation=https://github.com/kelseyhightower/lmktfy-register

        [Service]
        ExecStartPre=/usr/bin/wget -N -P /opt/bin http://storage.googleapis.com/lmktfy/lmktfy-register
        ExecStartPre=/usr/bin/chmod +x /opt/bin/lmktfy-register
        ExecStart=/opt/bin/lmktfy-register \
        --metadata=lmktfy_role=minion \
        --fleet-endpoint=unix:///var/run/fleet.sock \
        --api-endpoint=http://127.0.0.1:8080
        Restart=always
        RestartSec=10
    #Running nginx service with --net="host" is a necessary evil until running all lmktfy services in docker.
    - name: lmktfy-nginx.service
      command: start
      content: |
        [Unit]
        Description=LMKTFY Nginx Service
        After=network-online.target
        Requires=network-online.target
        After=docker.service
        Requires=docker.service
        [Service]
        ExecStartPre=/opt/bin/git-lmktfy-nginx.sh
        ExecStartPre=-/usr/bin/docker rm lmktfy_nginx
        ExecStart=/usr/bin/docker run --rm --net="host" -p "443:443" -t --name "lmktfy_nginx" lmktfy_nginx
        ExecStop=/usr/bin/docker stop lmktfy_nginx
        Restart=always
        RestartSec=15
