kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcsc001
spec:
  storageClassName: "portworx-io-priority-high"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
