kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kubelet-user-kube-proxy-binding
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:nodes
- kind: User
  apiGroup: rbac.authorization.k8s.io
  # Legacy node ID
  name: kubelet
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:node-proxier
