apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    storage: "local"
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  localStorage:
    path: "/tmp"
    nodeName: "test-node"
