apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: system.event-exporter
  annotations:
    kubernetes.io/description: 'Policy used by the event-exporter addon.'
    # TODO: event-exporter should run with the default seccomp profile
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    kubernetes.io/cluster-service: 'true'
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  privileged: false
  allowPrivilegeEscalation: true
  volumes:
  - 'hostPath'
  - 'secret'
  # TODO: This only needs a hostPath to read /etc/ssl/certs,
  #   but it should be able to just include these in the image.
  allowedHostPaths:
    - pathPrefix: /etc/ssl/certs
  hostNetwork: false
  hostIPC: false
  hostPID: false
  # TODO: This doesn't need to run as root.
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
