apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: calico-etcd
  name: calico-etcd
  namespace: kube-system
spec:
  clusterIP: 10.0.0.17
  ports:
    - port: 6666
  selector:
    k8s-app: calico-etcd
---
apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: calico-etcd
  namespace: kube-system
spec:
  serviceName: calico-etcd
  replicas: 1
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        kubernetes.io/cluster-service: "true"
        k8s-app: calico-etcd
    spec:
      hostNetwork: true
      containers:
        - name: calico-etcd
          image: gcr.io/google_containers/etcd:2.2.1
          env:
            - name: CALICO_ETCD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/bin/sh","-c"]
          args: ["/usr/local/bin/etcd --name=calico --data-dir=/var/etcd/calico-data --advertise-client-urls=http://$CALICO_ETCD_IP:6666 --listen-client-urls=http://0.0.0.0:6666 --listen-peer-urls=http://0.0.0.0:6667"]
          volumeMounts:
            - name: var-etcd
              mountPath: /var/etcd
  volumeClaimTemplates:
    - metadata:
        name: var-etcd
        annotations:
          volume.alpha.kubernetes.io/storage-class: anything
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: calico-policy-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: calico-policy
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        kubernetes.io/cluster-service: "true"
        k8s-app: calico-policy
    spec:
      hostNetwork: true
      containers:
        - name: calico-policy-controller
          image: calico/kube-policy-controller:v0.2.0
          env:
            - name: ETCD_ENDPOINTS
              value: "http://10.0.0.17:6666"
            - name: K8S_API
              value: "http://kubernetes:443"
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
