apiVersion: v1beta3
kind: Service
metadata: 
  labels: 
    name: influxGrafana
    lmktfy.io/cluster-service: "true"
  name: monitoring-grafana
spec: 
  targetPort: 80
  port: 80
  selector: 
    name: influxGrafana
    lmktfy.io/cluster-service: "true"


