apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube:%(kube_version)s
    command:
    - /hyperkube
    - apiserver
    - --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --advertise-address=$private_ipv4
    - --allow-privileged=true
    - --bind-address=0.0.0.0
    - --client-ca-file=/etc/kubernetes/ssl/ca.crt
    - --cloud-provider=aws
    - --etcd-servers=%(etcd_endpoints)s
    - --etcd-prefix=%(cluster_prefix)s
    - --event-ttl=24h0m0s
    - --insecure-bind-address=0.0.0.0
    - --insecure-port=8080
    - --master-service-namespace=kube-system
    - --runtime-config=extensions/v1beta1/deployments=true,extensions/v1beta1/daemonsets=true
    - --secure-port=443
    - --service-account-key-file=/etc/kubernetes/ssl/kube-master.key
    - --service-cluster-ip-range=%(service_ip_range)s
    - --tls-cert-file=/etc/kubernetes/ssl/kube-master.crt
    - --tls-private-key-file=/etc/kubernetes/ssl/kube-master.key
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
