kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-cni-config
  namespace: kube-system
data:
  calico.cni.fullconfig: |-
    {
        "name": "k8s-pod-network",
        "type": "calico",
        "etcd_authority": "10.0.0.17:6666",
        "log_level": "info",
        "ipam": {
            "type": "host-local",
            "subnet": "usePodCidr"
        },
        "policy": {
            "type": "k8s"
        },
        "kubernetes": {
            "kubeconfig": "/var/lib/kubelet/kubeconfig"
        }
    }
