kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: calico-typha-vertical-autoscaler
  namespace: kube-system
  labels:
    k8s-app: calico-typha-autoscaler
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      k8s-app: calico-typha-autoscaler
      name: calico-typha-vertical-autoscaler
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: calico-typha-autoscaler
        name: calico-typha-vertical-autoscaler
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
        - image: gcr.io/google_containers/cpvpa-amd64:v0.6.0
          name: autoscaler
          command:
            - /cpvpa
            - --target=deployment/calico-typha
            - --namespace=kube-system
            - --logtostderr=true
            - --poll-period-seconds=30
            - --v=2
            - --config-file=/etc/config/typha-autoscaler
          volumeMounts:
            - name: config
              mountPath: /etc/config
      volumes:
        - name: config
          configMap:
            name: calico-typha-vertical-autoscaler
      serviceAccountName: calico-cpva
