apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gce:podsecuritypolicy:event-exporter
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - policy
  resourceNames:
  - gce.event-exporter
  resources:
  - podsecuritypolicies
  verbs:
  - use
