apiVersion: v1
kind: ReplicationController
metadata:
  name: haproxy-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      volumes:
      - name: haproxy-cfg
        secret:
          secretName: haproxy-cfg
      containers:
      - name: haproxy
        image: haproxy:1
        args:
        - haproxy
        - -db
        - -f
        - /etc/haproxy/haproxy.cfg
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/haproxy
          name: haproxy-cfg
