apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: heapster
  ports:
  - port: 80
    targetPort: 8082
