apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1.2.0-beta.2
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.2.0-beta.2
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.2.0-beta.2
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.2.0-beta.2
    spec:
      containers:
        - image: REGISTRY/hyperkube-ARCH:VERSION
          name: heapster
          resources:
            # keep request = limit to keep this container in guaranteed class
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes:'http://$kube-apiserver'
