apiVersion: v1
kind: Service
metadata:
  name: echoheadersx
  labels:
    app: echoheaders
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30301
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders
---
apiVersion: v1
kind: Service
metadata:
  name: echoheadersy
  labels:
    app: echoheaders
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30284
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: echoheaders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoheaders
        image: bprashanth/echoserver:0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: IngressPoint
metadata:
  name: echomap
spec:
  host: echo
  pathMap:
    "foo.echo.com":
    - url: "/x/*"
      service:
        name: echoheadersx
        namespace: default
        port: 80
    - url: "/y/*"
      service:
        name: echoheadersy
        namespace: default
        port: 80
    "bar.echo.com":
    - url: "/x/*"
      service:
        name: echoheadersx
        namespace: default
        port: 80
