apiVersion: v1
clusters:
- cluster:
    server:  http://kube-00:8080
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-key: /etc/secret-volume/kube-client-key
