apiVersion: v1
clusters:
- cluster:
    server: http://kube00:8080
  name: beenger
contexts:
- context:
    cluster: beenfer
    user: cluster-admin
  name: openshift
current-context: openshift
kind: Config
preferences: {}
users:
- name: cluster-admin
  user:  
    client-key: /etc/secret-volume/kube-client-key
