apiVersion: v1
kind: Pod
metadata:
  name: etcd-version-monitor
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: etcd-version-monitor
    image: gcr.io/google_containers/etcd_version_monitor:test
    command:
    - /bin/etcd-version-monitor
