---
# Install etcd
- hosts: etcd
  sudo: yes
  roles:
        - common
        - etcd
  tags:
        - etcd

# install kube
- hosts: masters
  sudo: yes
  roles:
        - common
        - kubernetes
        - master
  tags:
        - masters

- hosts: minions
  sudo: yes
  roles:
        - common
        - kubernetes
        - minion
  tags:
        - minions
