apiVersion: v1
kind: Service
metadata:
  name: redis-worker
  labels:
    name: redis-worker
spec:
  ports:
    # the port that this service should serve on
  - port: 6379
  selector:
    name: redis-worker
