apiVersion: v1
kind: Pod
metadata:
  name: invalid-pod
spec:
  containers:
  - name: kubernetes-serve-hostname
    image: gcr.kubernetes.io/serve_hostname
    resources:
      limits:
        cpu: "3"
        memory: 100Mi
