apiVersion: v1
kind: Service
metadata:
  name: rsyslog-service
  labels:
    app: rsyslog
spec:
  type: ClusterIP
  ports:
  - port: 514
    protocol: TCP
    name: syslog-tcp
  - port: 514
    protocol: UDP
    name: syslog-udp
  selector:
    app: rsyslog
